[package]
name = "rscape"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features=["bevy_dev_tools"] } 
bevy_egui = "0.37.1"
bevy_heightmap = "0.7.0"
libnoise = "1.2.0"
rand = "0.9.2"
strum = "0.27.2"
strum_macros = "0.27.2"
